version: '3'
services:
  app:
    build: .
    tty: true
    ports:
      - 3000:3000
    volumes:
      - .:/react-intro
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true